apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: github.com
spec:
  hosts:
    - github.com
    - pkg-containers.githubusercontent.com
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  location: MESH_EXTERNAL
