apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: ghcr.io
spec:
  hosts:
    - ghcr.io
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  location: MESH_EXTERNAL
