[package]
name = "trivy-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-to-html = "0.1"
askama = "0.12"
axum-macros = "0.3"
axum = { version = "0.6", features = ["json", "macros"] }
clap = { version = "4", features = ["derive", "env", "cargo"] }
maud = "0.25"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full", "tracing"] }
tower-http = { version = "0.4", features = ["fs", "trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-tree = "0.2"
tracing = "0.1"
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
