[package]
name = "trivy-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-to-html = "0.2"
askama = "0.12"
axum-macros = "0.4"
axum = { version = "0.7", features = ["json", "macros"] }
chrono = "0.4"
clap = { version = "4", features = ["derive", "env", "cargo"] }
maud = "0.26"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full", "tracing"] }
tower-http = { version = "0.5", features = ["fs", "trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-tree = "0.3"
tracing = "0.1"
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
x509-parser = "0.16"

[dev-dependencies]
pretty_assertions = "1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
