apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-server
spec:
  selector:
    matchLabels:
      app: trivy-server
  template:
    metadata:
      labels:
        app: trivy-server
        version: 1.0.0
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: trivy-server
          image: ghcr.io/aquasecurity/trivy:0.53.0
          args:
            - "server"
            - "--listen"
            - "0.0.0.0:4954"
            - "--cache-backend"
            - "redis://redis-server.trivy-web.svc.cluster.local:6379"
          ports:
            - containerPort: 4954
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1000m"
              memory: 2Gi
          volumeMounts:
            - name: cache
              mountPath: /.cache
      volumes:
        - name: cache
          emptyDir: {}
