apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-web
  serviceName: redis-web
  template:
    metadata:
      labels:
        app: redis-web
        version: 1.0.0
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          args:
            - "--bind"
            - "0.0.0.0"
          resources:
            requests:
              cpu: '100m'
              memory: 128Mi
            limits:
              cpu: '1'
              memory: 2Gi
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
