apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trivy-server
spec:
  minReplicas: 1
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trivy-server
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 200
          type: Utilization
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 200
          type: Utilization
