#apiVersion: networking.istio.io/v1beta1
#kind: Gateway
#metadata:
#  name: trivy-web
#spec:
#  selector:
#    istio: ingressgateway
#  servers:
#    - port:
#        number: 443
#        name: https
#        protocol: HTTPS
#      tls:
#        mode: SIMPLE
#        credentialName: cert-thaller-rocks
#      hosts:
#        - trivy-web.thaller.rocks
