apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trivy-web
spec:
  minReplicas: 1
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trivy-web
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 200
          type: Utilization
      type: Resource
