apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
        version: 1.59.0
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.59.0
          ports:
            - name: grpc
              containerPort: 16685
            - name: http
              containerPort: 16686
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 5
              memory: 2Gi
